services:
    database:
        container_name: 'friendevent_backend_database'
        image: 'mysql:9'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: friendevent
        ports:
            - '3306'
        volumes:
            - 'friendevent_backend_mysql_data:/var/lib/mysql'
    backend:
        container_name: 'friendevent_backend'
        build: .
        ports:
            - '8082:80'

volumes:
    friendevent_backend_mysql_data:

